#!/usr/bin/env python3
"""Build data/gazetteer.yaml: the joined base-EV + ConEx map of every system
and stellar object, plus reverse-resolution of every ID ConEx's missions use.

Sources (both parsed with evutils, field layouts from each fork's own TMPLs):
- base scenario: EV Data from Escape Velocity 1.0.4 (local only, not committed;
  see vendor/paulricheson/PROVENANCE.md for where it came from)
- plugin: ConEx 1.2. Plugin resources override base resources at the same ID.

Usage: python3 data/build_gazetteer.py [<EV Data.rsrc> <ConEx1.2.rsrc>]
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
from evutils import rfork, tmpl  # noqa: E402

BASE = REPO / "vendor/expanded/Escape Velocity 1.0.4 ƒ/EV Data.rsrc"
PLUGIN = REPO / "vendor/expanded/ConEx 1.2/ConEx1.2.rsrc"

# mïsn fields that reference stellar objects / systems
STEL_FIELDS = ("AvailStel", "TravelStel", "ReturnStel")
SYST_FIELDS = ("ShipSyst", "AuxShipSyst")

# Special encodings, per the EV Bible (vendor/ev-bible-extracted/, EVO edition;
# classic EV uses the same scheme with smaller ranges)
STEL_SPECIALS = {
    -1: "none",
    -2: "random inhabited stellar",
    -3: "random uninhabited stellar",
    -4: "the stellar where the mission was accepted",
}
SYST_SPECIALS = {
    -1: "the system where the mission was accepted",
    -2: "any random system",
    -3: "TravelStel's system",
    -4: "ReturnStel's system",
    -5: "a system adjacent to the initial system",
    -6: "whatever system the player is in",
}


def special(value, table, govts):
    if value in table:
        return table[value]
    for base_code, what in ((10000, "of govt"), (15000, "of an ally of govt"),
                            (20000, "of any govt but"), (25000, "of an enemy of govt")):
        if base_code <= value < base_code + 128:
            gid = 128 + value - base_code
            gname = govts[gid][0] if gid in govts else f"?{gid}"
            return f"random {what} {gid} ({gname})"
    return None


def load(path):
    fork = rfork.parse(rfork.unwrap_appledouble(path.read_bytes()))
    templates = tmpl.templates_in(fork)
    out = {}
    for r in fork.resources:
        fields = None
        if r.rtype in templates:
            try:
                fields = dict_of(tmpl.decode(templates[r.rtype], r.data))
            except (ValueError, IndexError):
                fields = None
        out.setdefault(r.rtype, {})[r.rid] = (r.name, fields)
    return out


def dict_of(pairs):
    # TMPL labels repeat (Con1..Con16 are unique, but be safe): first wins
    d = {}
    for label, value in pairs:
        d.setdefault(label, value)
    return d


def overlay(base, plugin, rtype):
    """id -> (name, fields, source) with plugin winning at the same ID."""
    merged = {}
    for rid, (name, fields) in base.get(rtype, {}).items():
        merged[rid] = (name, fields, "base")
    for rid, (name, fields) in plugin.get(rtype, {}).items():
        src = "conex-override" if rid in merged else "conex"
        merged[rid] = (name, fields, src)
    return merged


def q(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    base_path = Path(sys.argv[1]) if len(sys.argv) > 2 else BASE
    plug_path = Path(sys.argv[2]) if len(sys.argv) > 2 else PLUGIN
    base, plugin = load(base_path), load(plug_path)

    systems = overlay(base, plugin, "sÿst")
    spobs = overlay(base, plugin, "spöb")
    govts = overlay(base, plugin, "gövt")
    descs = overlay(base, plugin, "dësc")

    def govt_name(gid):
        if gid in (-1, None):
            return None
        return govts[gid][0] if gid in govts else f"UNRESOLVED({gid})"

    findings = []
    lines = [
        "# Gazetteer of the ConEx universe: base EV 1.0.4 overlaid with ConEx 1.2.",
        "# Generated by data/build_gazetteer.py — regenerate rather than editing.",
        "# IDs are resource IDs. source: base | conex (new) | conex-override.",
        "",
        "systems:",
    ]
    for rid in sorted(systems):
        name, f, src = systems[rid]
        if f is None:
            continue
        links = [f[k] for k in f if k.startswith("Con") and f[k] != -1]
        navs = [f[f"Nav{i}"] for i in range(1, 5) if f.get(f"Nav{i}", -1) != -1]
        lines.append(f"  {rid}:")
        lines.append(f"    name: {q(name or '')}")
        if src == "conex-override":
            lines.append(f"    replaces: {q(base['sÿst'][rid][0] or '')}")
        lines.append(f"    source: {src}")
        lines.append(f"    x: {f['xPos']}")
        lines.append(f"    y: {f['yPos']}")
        lines.append(f"    links: {links}")
        lines.append(f"    stellars: {navs}")
        g = govt_name(f.get("Govt"))
        if g:
            lines.append(f"    govt: {q(g)}")
        for link in links:
            if link == rid:
                findings.append(f"sÿst {rid} {name!r} lists itself as a hyperspace link")
            elif link not in systems or systems[link][1] is None:
                findings.append(f"sÿst {rid} {name!r} links to nonexistent system {link}")
        for nav in navs:
            if nav < 128:
                findings.append(f"sÿst {rid} {name!r} has invalid Nav entry {nav} (IDs start at 128)")
            elif nav not in spobs or spobs[nav][1] is None:
                findings.append(f"sÿst {rid} {name!r} lists nonexistent stellar {nav}")

    lines.append("")
    lines.append("stellars:")
    parent_of = {}
    for rid in sorted(spobs):
        name, f, src = spobs[rid]
        if f is None:
            continue
        # prefer the system whose Nav list carries this stellar; the spöb's
        # own System field is a fallback (base EV leaves some stale)
        holders = [
            sid for sid in sorted(systems)
            if systems[sid][1] and rid in [
                systems[sid][1].get(f"Nav{i}") for i in range(1, 5)
            ]
        ]
        parent = holders[0] if holders else f.get("System")
        parent_of[rid] = parent
        lines.append(f"  {rid}:")
        lines.append(f"    name: {q(name or '')}")
        if src == "conex-override":
            lines.append(f"    replaces: {q(base['spöb'][rid][0] or '')}")
        lines.append(f"    source: {src}")
        if parent in systems:
            lines.append(f"    system: {parent}  # {systems[parent][0]}")
        else:
            lines.append(f"    system: {parent}  # UNRESOLVED")
        g = govt_name(f.get("Govt"))
        if g:
            lines.append(f"    govt: {q(g)}")
        lines.append(f"    tech: {f.get('TechLevel')}")
        lines.append(f"    landing_desc: {rid if rid in descs else None}")

    lines.append("")
    lines.append("# Every stellar/system reference in ConEx's mïsn resources,")
    lines.append("# reverse-resolved. Anything UNRESOLVED is an extraction bug")
    lines.append("# or a genuine 1997 bug — both are findings.")
    lines.append("mission_references:")
    unresolved = []
    for rid in sorted(plugin.get("mïsn", {})):
        name, f = plugin["mïsn"][rid]
        if f is None:
            continue
        lines.append(f"  {rid}:")
        lines.append(f"    name: {q(name or '')}")
        for field in STEL_FIELDS + SYST_FIELDS:
            v = f.get(field)
            if v in (-1, None):
                continue
            is_stel = field in STEL_FIELDS
            table = spobs if is_stel else systems
            if 128 <= v and v in table and table[v][1] is not None:
                where = table[v][0]
                if is_stel and parent_of.get(v) in systems:
                    where = f"{where} ({systems[parent_of[v]][0]})"
                lines.append(f"    {field}: {v}  # {where}")
                continue
            note = special(v, STEL_SPECIALS if is_stel else SYST_SPECIALS, govts)
            if note:
                lines.append(f"    {field}: {v}  # special: {note}")
            else:
                lines.append(f"    {field}: {v}  # UNRESOLVED")
                unresolved.append((rid, name, field, v))

    lines.append("")
    lines.append("# Referential problems found while joining — genuine 1997 bugs")
    lines.append("# unless they turn out to be extraction errors. Phase 3 leads.")
    lines.append("findings:")
    for finding in findings + [
        f"mïsn {rid} {name!r}: {field} = {v} resolves to nothing"
        for rid, name, field, v in unresolved
    ]:
        lines.append(f"  - {q(finding)}")

    out = REPO / "data" / "gazetteer.yaml"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_sys = sum(1 for v in systems.values() if v[1])
    n_spob = sum(1 for v in spobs.values() if v[1])
    print(f"wrote {out}: {n_sys} systems, {n_spob} stellars, "
          f"{len(plugin.get('mïsn', {}))} missions")
    if unresolved:
        print(f"\n{len(unresolved)} UNRESOLVED references:")
        for rid, name, field, v in unresolved:
            print(f"  mïsn {rid} {name!r}: {field} = {v}")
    else:
        print("all mission references resolved")


if __name__ == "__main__":
    main()
